// Generated by tools/xna-assemblies from XNA 4.0's Microsoft.Xna.Framework.Storage.dll: its 3 public types, forwarded to CNA.XnaCompat.
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Microsoft.Xna.Framework.Storage.StorageContainer))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Microsoft.Xna.Framework.Storage.StorageDevice))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Microsoft.Xna.Framework.Storage.StorageDeviceNotConnectedException))]
