using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace CNA.XnaCompat.Generators;

/// <summary>
/// Lets a game's <c>using</c> of a namespace that .NET Framework 4 had and .NET does not compile, as
/// it compiled for the game's author (CSX-131). Visual Studio added such directives on its own --
/// <c>using System.Runtime.Remoting.Messaging;</c> for a completed <c>Header</c> -- and a directive
/// naming a namespace with no types is an error (CS0234) even when nothing uses it:
/// WilliamKluge/SuperSmashPolls has that one. For each such namespace the compilation lacks, an
/// internal placeholder type gives the namespace a member, so the directive binds; a type the game
/// does use from it is still missing, and still an error. The list is every namespace of .NET
/// Framework 4's mscorlib, System, System.Core, System.Xml, System.Xml.Linq, System.Data,
/// System.Runtime.Serialization, System.Net and System.Drawing that .NET 8's reference assemblies
/// do not have, counting the namespaces of their type forwarders, which make a namespace exist too. <c>&lt;CnaNetFxNamespaces&gt;false&lt;/CnaNetFxNamespaces&gt;</c> turns it off.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class NetFxNamespacesGenerator : IIncrementalGenerator
{
    private static readonly HashSet<string> NetFx40Only = new(System.StringComparer.Ordinal)
    {
        "System.Data.ProviderBase", "System.Deployment", "System.Deployment.Internal",
        "System.Deployment.Internal.Isolation", "System.Deployment.Internal.Isolation.Manifest",
        "System.Diagnostics.Contracts.Internal", "System.Drawing.Internal", "System.Dynamic.Utils",
        "System.Internal", "System.Linq.Expressions.Compiler", "System.Linq.Parallel", "System.Management",
        "System.Management.Instrumentation", "System.Net.Configuration", "System.Reflection.Cache",
        "System.Runtime.Hosting", "System.Runtime.InteropServices.Expando",
        "System.Runtime.InteropServices.TCEAdapterGen", "System.Runtime.Remoting.Activation",
        "System.Runtime.Remoting.Channels", "System.Runtime.Remoting.Contexts",
        "System.Runtime.Remoting.Lifetime", "System.Runtime.Remoting.Messaging",
        "System.Runtime.Remoting.Metadata", "System.Runtime.Remoting.Metadata.W3cXsd2001",
        "System.Runtime.Remoting.Proxies", "System.Runtime.Remoting.Services",
        "System.Runtime.Serialization.Configuration", "System.Runtime.Serialization.Diagnostics",
        "System.Security.Authentication.ExtendedProtection.Configuration", "System.Security.Util",
        "System.StubHelpers", "System.Xml.Serialization.Advanced", "System.Xml.Serialization.Configuration",
    };

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValueProvider<bool> enabled = context.AnalyzerConfigOptionsProvider.Select(static (options, _) =>
            !options.GlobalOptions.TryGetValue("build_property.CnaNetFxNamespaces", out string? value)
            || !string.Equals(value?.Trim(), "false", System.StringComparison.OrdinalIgnoreCase));

        IncrementalValuesProvider<string> named = context.SyntaxProvider.CreateSyntaxProvider(
            static (node, _) => node is UsingDirectiveSyntax { Alias: null, Name: not null } directive
                && directive.StaticKeyword.IsKind(SyntaxKind.None),
            static (syntax, _) => string.Concat(((UsingDirectiveSyntax)syntax.Node).Name!.ToString().Where(c => !char.IsWhiteSpace(c))))
            .Where(static name => NetFx40Only.Contains(name));

        context.RegisterSourceOutput(
            named.Collect().Combine(context.CompilationProvider).Combine(enabled),
            static (output, input) =>
            {
                ((ImmutableArray<string> names, Compilation compilation), bool on) = input;
                string[] missing = names.Distinct().Where(name => !Exists(compilation, name)).OrderBy(name => name, System.StringComparer.Ordinal).ToArray();
                if (on && missing.Length > 0)
                {
                    output.AddSource("NetFxNamespaces.g.cs", Render(missing));
                }
            });
    }

    private static bool Exists(Compilation compilation, string name)
    {
        INamespaceSymbol? current = compilation.GlobalNamespace;
        foreach (string segment in name.Split('.'))
        {
            current = current?.GetNamespaceMembers().FirstOrDefault(member => member.Name == segment);
        }

        return current is not null;
    }

    private static string Render(IEnumerable<string> namespaces)
    {
        var source = new StringBuilder("// <auto-generated/> CNA.XnaCompat: namespaces .NET Framework 4 had (CSX-131).\n");
        foreach (string name in namespaces)
        {
            source.Append("namespace ").Append(name)
                .Append(" { [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)] internal static class CnaNetFx40Namespace { } }\n");
        }

        return source.ToString();
    }
}
