using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace CNA.XnaCompat.Generators;

/// <summary>
/// Gives a game's calls to <c>List&lt;T&gt;.ForEach</c> the behaviour of the .NET Framework 4.0
/// that XNA 4.0 games target: the walk reads the list's count afresh at each step, so an element
/// the action appends is visited, and changing the list never throws. .NET Framework 4.5 added the
/// <c>InvalidOperationException</c> only for applications that target 4.5 or later
/// (<c>BinaryCompatibility.TargetsAtLeast_Desktop_V4_5</c>); .NET Core throws for every one.
/// escape-from-enceladus's event manager activates events from an event's own update, inside
/// <c>_activeEvents.ForEach</c>, as soon as its first room starts.
///
/// Each call site is intercepted (C# interceptors, namespace <c>CNA.XnaCompat.NetFx40</c>, which
/// CNA.XnaCompat.targets enables) -- the game's source is not touched, and nothing else in the
/// process changes. <c>&lt;CnaNetFx40ListForEach&gt;false&lt;/CnaNetFx40ListForEach&gt;</c> turns it off.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class NetFx40ListForEachGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValueProvider<bool> enabled = context.AnalyzerConfigOptionsProvider.Select(static (options, _) =>
            !options.GlobalOptions.TryGetValue("build_property.CnaNetFx40ListForEach", out string? value)
            || !string.Equals(value?.Trim(), "false", System.StringComparison.OrdinalIgnoreCase));

        IncrementalValuesProvider<string> locations = context.SyntaxProvider.CreateSyntaxProvider(
            static (node, _) => node is InvocationExpressionSyntax
            {
                Expression: MemberAccessExpressionSyntax { Name.Identifier.ValueText: "ForEach" },
            },
            static (syntax, cancellation) => Locate(syntax, cancellation))
            .Where(static location => location is not null)!;

        context.RegisterSourceOutput(
            locations.Collect().Combine(enabled),
            static (output, input) =>
            {
                (ImmutableArray<string> attributes, bool on) = input;
                if (on && !attributes.IsEmpty)
                {
                    output.AddSource("NetFx40ListForEach.g.cs", Render(attributes));
                }
            });
    }

    private static string? Locate(GeneratorSyntaxContext syntax, CancellationToken cancellation)
    {
        var invocation = (InvocationExpressionSyntax)syntax.Node;
        if (syntax.SemanticModel.GetSymbolInfo(invocation, cancellation).Symbol is not IMethodSymbol method
            || method.IsStatic
            || method.Parameters.Length != 1
            || method.ContainingType.OriginalDefinition.ToDisplayString() != "System.Collections.Generic.List<T>")
        {
            return null;
        }

#pragma warning disable RSEXPERIMENTAL002 // The interceptor location API, experimental in Roslyn 4.11.
        return syntax.SemanticModel.GetInterceptableLocation(invocation, cancellation)?.GetInterceptsLocationAttributeSyntax();
#pragma warning restore RSEXPERIMENTAL002
    }

    private static string Render(ImmutableArray<string> attributes)
    {
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated>CNA.XnaCompat: List<T>.ForEach as .NET Framework 4.0 ran it.</auto-generated>");
        source.AppendLine("#nullable disable");
        source.AppendLine("namespace System.Runtime.CompilerServices");
        source.AppendLine("{");
        source.AppendLine("    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]");
        source.AppendLine("    file sealed class InterceptsLocationAttribute : global::System.Attribute");
        source.AppendLine("    {");
        source.AppendLine("        public InterceptsLocationAttribute(int version, string data) { }");
        source.AppendLine("    }");
        source.AppendLine("}");
        source.AppendLine();
        source.AppendLine("namespace CNA.XnaCompat.NetFx40");
        source.AppendLine("{");
        source.AppendLine("    file static class ListForEachInterceptor");
        source.AppendLine("    {");
        foreach (string attribute in attributes.Distinct())
        {
            source.Append("        ").AppendLine(attribute);
        }

        source.AppendLine("        public static void ForEach<T>(this global::System.Collections.Generic.List<T> list, global::System.Action<T> action)");
        source.AppendLine("        {");
        source.AppendLine("            if (action == null)");
        source.AppendLine("            {");
        source.AppendLine("                throw new global::System.ArgumentNullException(\"match\");");
        source.AppendLine("            }");
        source.AppendLine();
        source.AppendLine("            for (int i = 0; i < list.Count; i++)");
        source.AppendLine("            {");
        source.AppendLine("                action(list[i]);");
        source.AppendLine("            }");
        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine("}");
        return source.ToString();
    }
}
