using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace CNA.XnaCompat.Generators;

/// <summary>
/// Gives a game's calls to <c>Assembly.LoadFile</c> the identity rule of the .NET Framework that
/// XNA 4.0 games target: a file is one assembly in the application domain. LoadFile of a file the
/// application already loaded -- or one it would load for that name, its own reference beside it --
/// is that assembly, in either order (measured on .NET Framework 4 under Wine). .NET loads every
/// LoadFile into a context of its own, so the game ends up with two copies of the same types:
/// jacobdufault/forge-sample loads <c>GameLogic.dll</c> that way and then finds its renderers by the
/// types of the other copy, and draws nothing. A file the application would not load (a copy
/// elsewhere) still gets its own context, as .NET Framework gave it one.
///
/// Each call site is intercepted (C# interceptors, namespace <c>CNA.XnaCompat.NetFx40</c>, which
/// CNA.XnaCompat.targets enables) -- the game's source is not touched, and nothing else in the
/// process changes. <c>&lt;CnaNetFxAssemblyLoadFile&gt;false&lt;/CnaNetFxAssemblyLoadFile&gt;</c>
/// turns it off.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class NetFxAssemblyLoadFileGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValueProvider<bool> enabled = context.AnalyzerConfigOptionsProvider.Select(static (options, _) =>
            !options.GlobalOptions.TryGetValue("build_property.CnaNetFxAssemblyLoadFile", out string? value)
            || !string.Equals(value?.Trim(), "false", System.StringComparison.OrdinalIgnoreCase));

        IncrementalValuesProvider<string> locations = context.SyntaxProvider.CreateSyntaxProvider(
            static (node, _) => node is InvocationExpressionSyntax
            {
                Expression: MemberAccessExpressionSyntax { Name.Identifier.ValueText: "LoadFile" },
            },
            static (syntax, cancellation) => Locate(syntax, cancellation))
            .Where(static location => location is not null)!;

        context.RegisterSourceOutput(
            locations.Collect().Combine(enabled),
            static (output, input) =>
            {
                (ImmutableArray<string> attributes, bool on) = input;
                if (on && !attributes.IsEmpty)
                {
                    output.AddSource("NetFxAssemblyLoadFile.g.cs", Render(attributes));
                }
            });
    }

    private static string? Locate(GeneratorSyntaxContext syntax, CancellationToken cancellation)
    {
        var invocation = (InvocationExpressionSyntax)syntax.Node;
        if (syntax.SemanticModel.GetSymbolInfo(invocation, cancellation).Symbol is not IMethodSymbol method
            || !method.IsStatic
            || method.Parameters.Length != 1
            || method.ContainingType.ToDisplayString() != "System.Reflection.Assembly")
        {
            return null;
        }

#pragma warning disable RSEXPERIMENTAL002 // The interceptor location API, experimental in Roslyn 4.11.
        return syntax.SemanticModel.GetInterceptableLocation(invocation, cancellation)?.GetInterceptsLocationAttributeSyntax();
#pragma warning restore RSEXPERIMENTAL002
    }

    private static string Render(ImmutableArray<string> attributes)
    {
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated>CNA.XnaCompat: Assembly.LoadFile as .NET Framework loaded a file, once.</auto-generated>");
        source.AppendLine("#nullable disable");
        source.AppendLine("namespace System.Runtime.CompilerServices");
        source.AppendLine("{");
        source.AppendLine("    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]");
        source.AppendLine("    file sealed class InterceptsLocationAttribute : global::System.Attribute");
        source.AppendLine("    {");
        source.AppendLine("        public InterceptsLocationAttribute(int version, string data) { }");
        source.AppendLine("    }");
        source.AppendLine("}");
        source.AppendLine();
        source.AppendLine("namespace CNA.XnaCompat.NetFx40");
        source.AppendLine("{");
        source.AppendLine("    file static class AssemblyLoadFileInterceptor");
        source.AppendLine("    {");
        foreach (string attribute in attributes.Distinct())
        {
            source.Append("        ").AppendLine(attribute);
        }

        source.AppendLine("        public static global::System.Reflection.Assembly LoadFile(string path)");
        source.AppendLine("        {");
        source.AppendLine("            if (path != null && global::System.IO.Path.IsPathFullyQualified(path))");
        source.AppendLine("            {");
        source.AppendLine("                string full = global::System.IO.Path.GetFullPath(path);");
        source.AppendLine("                foreach (global::System.Reflection.Assembly loaded in global::System.AppDomain.CurrentDomain.GetAssemblies())");
        source.AppendLine("                {");
        source.AppendLine("                    if (!loaded.IsDynamic && string.Equals(loaded.Location, full, global::System.StringComparison.Ordinal))");
        source.AppendLine("                    {");
        source.AppendLine("                        return loaded;");
        source.AppendLine("                    }");
        source.AppendLine("                }");
        source.AppendLine();
        source.AppendLine("                if (global::System.AppContext.GetData(\"TRUSTED_PLATFORM_ASSEMBLIES\") is string trusted");
        source.AppendLine("                    && global::System.Array.IndexOf(trusted.Split(global::System.IO.Path.PathSeparator), full) >= 0)");
        source.AppendLine("                {");
        source.AppendLine("                    return global::System.Runtime.Loader.AssemblyLoadContext.Default.LoadFromAssemblyPath(full);");
        source.AppendLine("                }");
        source.AppendLine("            }");
        source.AppendLine();
        source.AppendLine("            return global::System.Reflection.Assembly.LoadFile(path);");
        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine("}");
        return source.ToString();
    }
}
