using System.Reflection;
using System.Reflection.Metadata;
using System.Reflection.PortableExecutable;

// Keeps src/XnaAssemblies in step with XNA 4.0 and CNA.XnaCompat: for each XNA runtime assembly,
// every public top-level type it defines must be forwarded to the facade type of the same name
// (nested types travel with their enclosing type). Checks by default and exits 1 on any drift;
// --write regenerates the Forwards.cs files. Run from the repository root:
//
//   XNA_REFERENCE_PATH=/path/to/xna/v4.0/assemblies dotnet run --project tools/xna-assemblies -c Release -- \
//       --facade src/CNA.XnaCompat/bin/Release/net8.0/CNA.XnaCompat.dll [--write]
string? xnaDir = Environment.GetEnvironmentVariable("XNA_REFERENCE_PATH");
string? facadePath = null;
string root = "src/XnaAssemblies";
bool write = false;
for (int i = 0; i < args.Length; i++)
{
    switch (args[i])
    {
        case "--xna": xnaDir = args[++i]; break;
        case "--facade": facadePath = args[++i]; break;
        case "--root": root = args[++i]; break;
        case "--write": write = true; break;
        default: Console.Error.WriteLine($"unknown argument {args[i]}"); return 2;
    }
}
if (xnaDir is null || facadePath is null)
{
    Console.Error.WriteLine("usage: [--xna DIR | XNA_REFERENCE_PATH=DIR] --facade CNA.XnaCompat.dll [--root src/XnaAssemblies] [--write]");
    return 2;
}

var facadeTypes = new HashSet<string>(Assembly.LoadFrom(facadePath).GetExportedTypes().Select(t => t.FullName!));
int problems = 0;
foreach (string project in Directory.GetDirectories(root).Order(StringComparer.Ordinal))
{
    string name = Path.GetFileName(project);
    string reference = Path.Combine(xnaDir, name + ".dll");
    if (!File.Exists(reference))
    {
        Console.Error.WriteLine($"{name}: no {reference}");
        problems++;
        continue;
    }

    using var pe = new PEReader(File.OpenRead(reference));
    MetadataReader md = pe.GetMetadataReader();
    var lines = new List<string>();
    foreach (TypeDefinitionHandle handle in md.TypeDefinitions)
    {
        TypeDefinition type = md.GetTypeDefinition(handle);
        if ((type.Attributes & TypeAttributes.VisibilityMask) != TypeAttributes.Public)
            continue;
        string ns = md.GetString(type.Namespace), metadataName = md.GetString(type.Name);
        if (!facadeTypes.Contains(ns + "." + metadataName))
        {
            Console.Error.WriteLine($"{name}: CNA.XnaCompat has no {ns}.{metadataName}");
            problems++;
            continue;
        }
        int tick = metadataName.IndexOf('`');
        string csName = tick < 0 ? metadataName
            : metadataName[..tick] + "<" + new string(',', int.Parse(metadataName[(tick + 1)..]) - 1) + ">";
        lines.Add($"[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::{ns}.{csName}))]");
    }
    lines.Sort(StringComparer.Ordinal);
    lines.Insert(0, $"// Generated by tools/xna-assemblies from XNA 4.0's {name}.dll: its {lines.Count} public types, forwarded to CNA.XnaCompat.");

    string forwards = Path.Combine(project, "Forwards.cs");
    string expected = string.Join('\n', lines) + "\n";
    if (write)
    {
        File.WriteAllText(forwards, expected);
        Console.WriteLine($"{name}: {lines.Count - 1} types");
    }
    else if (!File.Exists(forwards) || File.ReadAllText(forwards) != expected)
    {
        Console.Error.WriteLine($"{name}: Forwards.cs is out of date (rerun with --write)");
        problems++;
    }
    else
    {
        Console.WriteLine($"{name}: {lines.Count - 1} types forwarded");
    }
}
return problems == 0 ? 0 : 1;
