// Generated by tools/xna-assemblies from XNA 4.0's Microsoft.Xna.Framework.Xact.dll: its 7 public types, forwarded to CNA.XnaCompat.
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Microsoft.Xna.Framework.Audio.AudioCategory))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Microsoft.Xna.Framework.Audio.AudioEngine))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Microsoft.Xna.Framework.Audio.AudioStopOptions))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Microsoft.Xna.Framework.Audio.Cue))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Microsoft.Xna.Framework.Audio.RendererDetail))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Microsoft.Xna.Framework.Audio.SoundBank))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Microsoft.Xna.Framework.Audio.WaveBank))]
