namespace Microsoft.Xna.Framework.GamerServices;

public enum AvatarAnimationPreset
{
    Stand0 = 0,
    Stand1 = 1,
    Stand2 = 2,
    Stand3 = 3,
    Stand4 = 4,
    Stand5 = 5,
    Stand6 = 6,
    Stand7 = 7,
    Clap = 8,
    Wave = 9,
    Celebrate = 10,
    FemaleIdleCheckNails = 11,
    FemaleIdleLookAround = 12,
    FemaleIdleShiftWeight = 13,
    FemaleIdleFixShoe = 14,
    FemaleAngry = 15,
    FemaleConfused = 16,
    FemaleLaugh = 17,
    FemaleCry = 18,
    FemaleShocked = 19,
    FemaleYawn = 20,
    MaleIdleLookAround = 21,
    MaleIdleStretch = 22,
    MaleIdleShiftWeight = 23,
    MaleIdleCheckHand = 24,
    MaleAngry = 25,
    MaleConfused = 26,
    MaleLaugh = 27,
    MaleCry = 28,
    MaleSurprised = 29,
    MaleYawn = 30,
}
