// Generated by tools/xna-assemblies from XNA 4.0's Microsoft.Xna.Framework.Video.dll: its 3 public types, forwarded to CNA.XnaCompat.
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Microsoft.Xna.Framework.Media.Video))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Microsoft.Xna.Framework.Media.VideoPlayer))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Microsoft.Xna.Framework.Media.VideoSoundtrackType))]
