// Generated by tools/xna-assemblies from XNA 4.0's Microsoft.Xna.Framework.Input.Touch.dll: its 7 public types, forwarded to CNA.XnaCompat.
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Microsoft.Xna.Framework.Input.Touch.GestureSample))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Microsoft.Xna.Framework.Input.Touch.GestureType))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Microsoft.Xna.Framework.Input.Touch.TouchCollection))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Microsoft.Xna.Framework.Input.Touch.TouchLocation))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Microsoft.Xna.Framework.Input.Touch.TouchLocationState))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Microsoft.Xna.Framework.Input.Touch.TouchPanel))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(global::Microsoft.Xna.Framework.Input.Touch.TouchPanelCapabilities))]
